#!/usr/bin/env bash
# Test double for `update-grub`.
#
# It is not a stub that does nothing — it reproduces the one behaviour the whole
# GRUB safety argument rests on: /etc/grub.d/10_linux emits the default entry as
#
#     linux ... ${GRUB_CMDLINE_LINUX} ${GRUB_CMDLINE_LINUX_DEFAULT}
#
# with LINUX first and DEFAULT last. Without that ordering reproduced faithfully,
# the fixture test would pass while telling us nothing about whether appending to
# _DEFAULT actually wins.
#
# Usage: fake-update-grub.sh <grub-default> <dropin-dir> <grubcfg-out>

set -Eeuo pipefail

GRUB_DEFAULT="${1:?usage: fake-update-grub.sh <grub-default> <dropin-dir> <grubcfg-out>}"
DROPIN_DIR="${2:?}"
GRUBCFG_OUT="${3:?}"

read_vars() {
  (
    set +u
    GRUB_CMDLINE_LINUX=""
    GRUB_CMDLINE_LINUX_DEFAULT=""
    if [ -r "$GRUB_DEFAULT" ]; then
      # shellcheck source=/dev/null
      . "$GRUB_DEFAULT"
    fi
    if [ -d "$DROPIN_DIR" ]; then
      for f in "$DROPIN_DIR"/*; do
        [ -r "$f" ] || continue
        # shellcheck source=/dev/null
        . "$f"
      done
    fi
    printf 'LINUX\t%s\n' "$GRUB_CMDLINE_LINUX"
    printf 'DEFAULT\t%s\n' "$GRUB_CMDLINE_LINUX_DEFAULT"
  )
}

LINUX=""
DEFAULT=""
while IFS=$'\t' read -r key value; do
  case "$key" in
    LINUX) LINUX="$value" ;;
    DEFAULT) DEFAULT="$value" ;;
  esac
done < <(read_vars)

mkdir -p "$(dirname "$GRUBCFG_OUT")"
cat >"$GRUBCFG_OUT" <<EOF
# Generated by tests/fake-update-grub.sh — not a real grub.cfg.
menuentry 'Ubuntu' {
	linux	/boot/vmlinuz root=/dev/sda1 ro ${LINUX} ${DEFAULT}
	initrd	/boot/initrd.img
}
EOF

printf 'fake-update-grub: wrote %s\n' "$GRUBCFG_OUT"
