services:
  redis:
    image: daturaai/redis:7.4.2
    healthcheck:
      test: redis-cli ping
    environment:
      - REDIS_MODE=master
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped
    volumes:
      - redis_data:/data

  validator:
    image: daturaai/compute-subnet-validator:dev
    env_file: ./.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}
    expose:
      - ${INTERNAL_PORT}
    volumes:
      - ${HOST_WALLET_DIR}:/root/.bittensor/wallets
    depends_on:
      - redis

  connector:
    image: daturaai/compute-subnet-validator:dev
    env_file: ./.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - COMPUTE_APP_URI=wss://dev.lium.io
    command: pdm run src/connector.py
    volumes:
      - ${HOST_WALLET_DIR}:/root/.bittensor/wallets
    depends_on:
      - redis

volumes:
  redis_data:
