version: '3.7'

services:
  lium-watchtower:
    image: daturaai/lium-watchtower@sha256:5a33287a4edf51119243463fd4eba0ce6e9c75964219dc974e337b4febe9366a
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env
    environment:
      - WATCHTOWER_ENABLED=true
      - WATCHTOWER_IMAGE=daturaai/compute-subnet-executor-runner
      - WATCHTOWER_INTERVAL=300
      - WATCHTOWER_ENDPOINT_URL=https://validator.lium.io/api/digest
      - WATCHTOWER_VALIDATOR_HOTKEY=5F7X5UpKSr26KU3jKfpLmT8kuKtBNyHhEnfS8xtxPCqCb13p
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
