version: '3.7'

services:
  lium-watchtower:
    image: daturaai/lium-watchtower@sha256:c6f378988de5e1bcad0c69c37ffbed6a621193e8e76d3f356e309b7c83fc06c5
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.env:/app/.env
    environment:
      - WATCHTOWER_ENABLED=true
      - WATCHTOWER_IMAGE=daturaai/compute-subnet-executor-runner
      - WATCHTOWER_INTERVAL=300
      - WATCHTOWER_ENV_FILE_PATH=${PWD}/.env
