"""The attest-agent: what it proves, what it refuses, and what it cannot reach.

The TDX quote and the NVIDIA evidence are the two things a test process cannot produce —
there is no TDX here and no CC-capable GPU — so those two calls are the seam. Everything
around them is real: a real EC key generated by the real code, the real `report_data`
construction, the real routes.

That split is deliberate rather than convenient. The quote is opaque bytes from hardware;
what this suite can actually check is whether the agent asks for a quote over the *right*
64 bytes, and whether it ever produces two different ones for a single challenge. Both are
properties of this code, and both are where a bug would be silent on hardware.
"""

import hashlib
import json
from types import SimpleNamespace

import pytest
from attest_agent import evidence
from attest_agent.app import (
    BAD_REQUEST_DETAIL,
    NO_QUOTE_DETAIL,
    NonceLedger,
    create_app,
)
from attest_agent.config import Config
from attest_agent.identity import (
    RENTER_IDENTITY_DOMAIN_V1,
    IdentityError,
    gpu_uuid_digest,
    identity_digest,
    parse_nonce,
    report_data,
)
from attest_agent.tls import load_or_create
from fastapi.testclient import TestClient

NONCE = "11" * 32
OTHER_NONCE = "22" * 32
UUIDS = ["GPU-11111111-1111-1111-1111-111111111111", "GPU-22222222-2222-2222-2222-222222222222"]


@pytest.fixture
def config(tmp_path) -> Config:
    return Config(state_dir=tmp_path / "state")


@pytest.fixture
def quoted(monkeypatch) -> list[bytes]:
    """Record the report_data every quote was asked for, and return a stand-in quote."""
    asked: list[bytes] = []

    def fake_quote(report_data_bytes: bytes, *, timeout: int) -> str:
        asked.append(report_data_bytes)
        return json.dumps({"quote": "0x" + report_data_bytes.hex()[:16], "event_log": []})

    monkeypatch.setattr("attest_agent.app.tdx_quote", fake_quote)
    return asked


@pytest.fixture
def gpus(monkeypatch):
    monkeypatch.setattr(
        "attest_agent.app.gpu_uuids", lambda: (list(UUIDS), "2 GPU(s) read from NVML")
    )
    monkeypatch.setattr(
        "attest_agent.app.collect_gpu_evidence",
        lambda uuids, nonce, *, arch: evidence.GpuEvidence(
            uuids,
            {"nonce": nonce, "evidence_list": [{"gpu": 0}, {"gpu": 1}], "arch": arch},
            "stub evidence",
        ),
    )


@pytest.fixture
def client(config, quoted, gpus) -> TestClient:
    with TestClient(create_app(config)) as test_client:
        yield test_client


class TestReportData:
    def test_it_is_the_identity_digest_then_the_nonce(self):
        """64 bytes: 32 of identity, 32 of freshness. dstack zero-pads a short one, so the
        second half being exactly nonce-sized is what makes both halves fit."""
        key = b"\x01" * 91
        nonce = bytes.fromhex(NONCE)

        data = report_data(key, UUIDS, nonce)

        assert len(data) == 64
        assert data[:32] == identity_digest(key, UUIDS)
        assert data[32:] == nonce

    def test_the_identity_half_binds_the_tls_key(self):
        """Without the key in the quote, a relay attacker forwards a genuine quote from a
        CVM it does not own and the verifier cannot tell."""
        assert identity_digest(b"key-a", UUIDS) != identity_digest(b"key-b", UUIDS)

    def test_the_identity_half_binds_the_gpus(self):
        """FR-G6: the GPU claim travels inside the signature, so the host cannot rewrite it.
        (What it does NOT do is authenticate the GPUs — that is the ueids' job.)"""
        assert identity_digest(b"key", UUIDS) != identity_digest(b"key", UUIDS[:1])

    def test_the_identity_half_is_domain_separated_and_versioned(self):
        """The exact bytes, spelled out. A verifier reproduces this digest from the wire and
        nothing else, so the tag, the key encoding and the order are the wire contract — and
        the version lives INSIDE the hash, which is what makes a future recipe a new tag
        rather than the same 32 bytes read a second way."""
        key = b"\x01" * 91

        assert identity_digest(key, UUIDS) == hashlib.sha256(
            b"LIUM_RENTER_ATTEST_TLS_V1\x00" + key + gpu_uuid_digest(UUIDS)
        ).digest()

    def test_the_domain_tag_is_terminated(self):
        """Without the NUL, a longer future tag starting with this one could be made to
        collide by shifting bytes across the boundary between tag and key."""
        assert RENTER_IDENTITY_DOMAIN_V1.endswith(b"\x00")

    def test_an_untagged_digest_is_not_accepted_as_this_one(self):
        """The whole point of the tag: the same key material hashed without a stated purpose
        is a different value, so nothing hashed for another purpose can be read as this."""
        key = b"\x01" * 91

        assert identity_digest(key, UUIDS) != hashlib.sha256(
            key + gpu_uuid_digest(UUIDS)
        ).digest()

    def test_the_gpu_digest_does_not_depend_on_enumeration_order(self):
        """NVML's order varies with PCI topology; the same node must not attest differently
        after a reboot that reordered it."""
        assert gpu_uuid_digest(UUIDS) == gpu_uuid_digest(list(reversed(UUIDS)))

    def test_a_cvm_with_no_gpus_still_has_a_gpu_binding(self):
        """Not a special case: every quote carries a GPU binding of the same shape."""
        assert gpu_uuid_digest([]) == hashlib.sha256(b"").digest()

    def test_a_uuid_containing_the_separator_is_refused(self):
        """Otherwise {"a,b"} and {"a", "b"} digest identically, and one GPU set could
        impersonate another."""
        with pytest.raises(IdentityError, match="digest alike"):
            gpu_uuid_digest(["GPU-a,GPU-b"])

    def test_a_key_that_is_missing_is_refused(self):
        with pytest.raises(IdentityError, match="prove nothing"):
            identity_digest(b"", UUIDS)

    @pytest.mark.parametrize(
        "value", ["zz" * 32, "11" * 16, "11" * 48, ""], ids=["not-hex", "short", "long", "empty"]
    )
    def test_a_nonce_that_is_not_32_bytes_is_refused_not_reshaped(self, value):
        """An agent that pads or truncates a challenge produces a quote the verifier cannot
        match against what it issued — which reads as a failed attestation, not a bad request."""
        with pytest.raises(IdentityError):
            parse_nonce(value)


class TestTheTlsIdentity:
    def test_it_is_generated_on_first_use_and_kept(self, tmp_path):
        """A restarted agent keeps its identity, so a verifier that pinned the key does not
        have to re-pin after every restart."""
        first = load_or_create(tmp_path / "cert.pem", tmp_path / "key.pem")
        second = load_or_create(tmp_path / "cert.pem", tmp_path / "key.pem")

        assert first.public_key_der == second.public_key_der

    def test_the_private_key_is_not_world_readable(self, tmp_path):
        identity = load_or_create(tmp_path / "cert.pem", tmp_path / "key.pem")

        assert identity.key_path.stat().st_mode & 0o077 == 0

    def test_half_a_pair_is_regenerated_rather_than_half_used(self, tmp_path):
        """An interrupted first boot leaves one file. Continuing from it would give the
        agent an identity it cannot actually serve."""
        identity = load_or_create(tmp_path / "cert.pem", tmp_path / "key.pem")
        identity.key_path.unlink()

        assert (
            load_or_create(tmp_path / "cert.pem", tmp_path / "key.pem").public_key_der
            != identity.public_key_der
        )


class TestAttesting:
    def test_the_quote_is_taken_over_the_advertised_report_data(self, client, quoted):
        """The one thing a test can check that hardware cannot: that the bytes the agent
        SAYS it bound are the bytes it actually asked the hardware to sign."""
        answer = client.post("/v1/attest", json={"nonce": NONCE}).json()

        assert quoted[0].hex() == answer["report_data"]
        assert answer["report_data"].endswith(NONCE)

    def test_it_reports_the_gpus_it_bound(self, client):
        answer = client.post("/v1/attest", json={"nonce": NONCE}).json()

        assert answer["gpu_uuids"] == UUIDS
        assert answer["gpu_uuid_digest"] == gpu_uuid_digest(UUIDS).hex()

    def test_the_gpu_evidence_carries_the_same_nonce_as_the_quote(self, client):
        """Two halves of one trust check must not be assembled from two moments — that is
        the shape of a replay."""
        answer = client.post("/v1/attest", json={"nonce": NONCE}).json()

        assert answer["gpu_evidence"]["nonce"] == NONCE

    def test_the_gpu_evidence_is_submittable_to_nras_as_returned(self, client):
        """The ueids inside NRAS's answer are what decide the GPU set, and NRAS will not
        answer a bare evidence list. An agent that returned one would leave the validator
        holding evidence it cannot get judged."""
        answer = client.post("/v1/attest", json={"nonce": NONCE}).json()

        assert set(answer["gpu_evidence"]) == {"nonce", "evidence_list", "arch"}
        assert answer["gpu_evidence"]["evidence_list"]

    def test_a_different_nonce_gets_a_different_quote(self, client, quoted):
        client.post("/v1/attest", json={"nonce": NONCE})
        client.post("/v1/attest", json={"nonce": OTHER_NONCE})

        assert len(quoted) == 2
        assert quoted[0] != quoted[1]
        assert quoted[0][:32] == quoted[1][:32], "the identity half is the same CVM"

    def test_the_same_nonce_gets_the_same_answer_and_no_second_quote(self, client, quoted):
        """Idempotent, not amnesiac. A verifier retrying after a network timeout must not
        fail, and the agent must never produce two different quotes for one challenge."""
        first = client.post("/v1/attest", json={"nonce": NONCE}).json()
        second = client.post("/v1/attest", json={"nonce": NONCE}).json()

        assert first == second
        assert len(quoted) == 1

    @pytest.mark.parametrize(
        "body", [{}, {"nonce": "abc"}, {"nonce": "zz" * 32}], ids=["absent", "short", "not-hex"]
    )
    def test_a_malformed_nonce_is_422(self, client, body):
        response = client.post("/v1/attest", json=body)

        assert response.status_code == 422
        # One field, one constraint — so stating the requirement is strictly more useful to a
        # caller than pydantic's or `parse_nonce`'s reading of what they sent, and it does not
        # echo their input back or expose which validator rejected it.
        assert response.json()["detail"] == BAD_REQUEST_DETAIL

    def test_no_quote_is_503_rather_than_500(self, config, gpus, monkeypatch):
        """The guest agent being unreachable is a condition of this host right now, and a
        verifier that retries later may well succeed."""
        monkeypatch.setattr(
            "attest_agent.app.tdx_quote",
            lambda data, *, timeout: (_ for _ in ()).throw(
                evidence.EvidenceError("no guest agent")
            ),
        )
        with TestClient(create_app(config)) as client:
            response = client.post("/v1/attest", json={"nonce": NONCE})

        assert response.status_code == 503
        assert response.json()["detail"] == NO_QUOTE_DETAIL
        assert "no guest agent" not in response.json()["detail"], (
            "the exception's own text is for the log; the agent answers anyone who can reach "
            "its port, and that text is a view of the guest's internals"
        )

    def test_health_advertises_what_a_verifier_pins(self, client):
        health = client.get("/health").json()

        assert health["tls_public_key"]
        assert health["gpu_uuids"] == UUIDS
        assert health["gpu_uuid_digest"] == gpu_uuid_digest(UUIDS).hex()

    def test_the_agent_exposes_nothing_but_these_two_routes(self, client):
        """FR-E6: its ONLY job is answering trust checks. A route that could read or reach
        the workload would be a hole in the confidentiality promise, so the surface is
        asserted rather than assumed."""
        paths = {
            route.path
            for route in client.app.routes
            if getattr(route, "path", "").startswith(("/health", "/v1"))
        }

        assert paths == {"/health", "/v1/attest"}


class TestTheVerifiersHalf:
    """A nonce is only fresh if the party that issued it says so.

    The agent is idempotent by design, so replay protection cannot live there: only the
    verifier knows which nonces it issued and when. This is that half, written as the
    validator will use it — and it is here rather than in the validator repo so that the
    property is pinned next to the agent whose answers it judges.
    """

    def test_a_reused_nonce_is_rejected(self, client):
        issued: set[str] = set()

        def verify(nonce: str, answer: dict) -> bool:
            if nonce in issued:
                return False
            issued.add(nonce)
            return answer["report_data"].endswith(nonce)

        answer = client.post("/v1/attest", json={"nonce": NONCE}).json()

        assert verify(NONCE, answer) is True
        assert verify(NONCE, answer) is False, "the same answer must not pass twice"

    def test_an_answer_bound_to_another_nonce_is_rejected(self, client):
        answer = client.post("/v1/attest", json={"nonce": NONCE}).json()

        assert not answer["report_data"].endswith(OTHER_NONCE)


class TestTheNonceLedger:
    def test_it_is_bounded(self):
        """It is keyed on caller-supplied input, so an unbounded map is memory the caller
        controls."""
        ledger = NonceLedger(capacity=3)
        for index in range(10):
            ledger.put(f"{index:064x}", {"index": index})

        assert len(ledger) == 3

    def test_the_oldest_is_evicted_first(self):
        ledger = NonceLedger(capacity=2)
        ledger.put("a", {"n": "a"})
        ledger.put("b", {"n": "b"})
        ledger.put("c", {"n": "c"})

        assert ledger.get("a") is None
        assert ledger.get("c") == {"n": "c"}

    def test_a_read_keeps_an_entry_alive(self):
        """A verifier that keeps retrying one challenge should not have its answer evicted
        by unrelated traffic."""
        ledger = NonceLedger(capacity=2)
        ledger.put("a", {"n": "a"})
        ledger.put("b", {"n": "b"})
        ledger.get("a")
        ledger.put("c", {"n": "c"})

        assert ledger.get("a") == {"n": "a"}
        assert ledger.get("b") is None


class TestDegradingHonestly:
    def test_no_gpu_evidence_is_none_with_a_reason_never_an_empty_list(self):
        """ "This CVM holds no GPUs" and "this agent could not tell" lead to opposite
        decisions on the validator's side, so they must not share an encoding."""
        result = evidence.collect_gpu_evidence([], "aa" * 32)

        assert result.payload is None
        assert "no GPUs" in result.detail

    def test_a_build_without_the_nvidia_stack_says_so(self, monkeypatch):
        monkeypatch.setitem(__import__("sys").modules, "nv_attestation_sdk", None)
        result = evidence.collect_gpu_evidence(UUIDS, "aa" * 32)

        assert result.payload is None
        assert result.uuids == UUIDS

    def test_a_stack_that_fails_while_loading_degrades_instead_of_raising(self, monkeypatch):
        """Importing the NVIDIA stack does real work — it opens a log file in the working
        directory — so it can fail on a read-only rootfs for reasons that are not ImportError.
        An exception escaping here would 500 the route, which the validator reads as a broken
        agent rather than as one half of one answer being unavailable."""

        class Exploding:
            def __getattr__(self, name):
                raise PermissionError("verifier.log")

        monkeypatch.setitem(__import__("sys").modules, "nv_attestation_sdk", Exploding())
        result = evidence.collect_gpu_evidence(UUIDS, "aa" * 32)

        assert result.payload is None
        assert "could not be loaded" in result.detail

    def test_a_collector_that_returns_nothing_is_no_evidence_not_empty_evidence(
        self, monkeypatch
    ):
        """An empty evidence_list submitted to NRAS would come back describing zero GPUs,
        which reads as "this CVM holds none" — the opposite of "the collector came up
        empty"."""

        class FakeAttester:
            def set_name(self, name): ...
            def set_nonce(self, nonce): ...
            def set_claims_version(self, version): ...
            def set_ocsp_nonce_disabled(self, disabled): ...
            def add_verifier(self, **kwargs): ...

            def get_evidence(self, options=None):
                return []

        modules = __import__("sys").modules
        monkeypatch.setitem(
            modules,
            "nv_attestation_sdk",
            SimpleNamespace(
                attestation=SimpleNamespace(
                    Attestation=FakeAttester,
                    Devices=SimpleNamespace(GPU="gpu"),
                    Environment={"REMOTE": "remote"},
                )
            ),
        )
        monkeypatch.setitem(
            modules,
            "verifier",
            SimpleNamespace(cc_admin=SimpleNamespace(collect_gpu_evidence_remote=lambda n: [])),
        )
        result = evidence.collect_gpu_evidence(UUIDS, "aa" * 32)

        assert result.payload is None
        assert "returned nothing" in result.detail

    def test_no_nvml_is_not_a_crash(self, monkeypatch):
        monkeypatch.setitem(__import__("sys").modules, "pynvml", None)
        uuids, detail = evidence.gpu_uuids()

        assert uuids == []
        assert detail

    def test_an_nvml_failure_names_the_state_without_quoting_the_driver(self, monkeypatch):
        """`detail` reaches whoever can reach the agent's port. It has to say WHICH of the
        four states this CVM is in, because that is what the validator acts on — and it must
        not carry NVML's own text, which describes the guest rather than the state."""

        class FakeNvml:
            @staticmethod
            def nvmlInit():
                raise RuntimeError("libnvidia-ml.so.1: cannot open shared object file")

        monkeypatch.setitem(__import__("sys").modules, "pynvml", FakeNvml)
        uuids, detail = evidence.gpu_uuids()

        assert uuids == []
        assert "NVML did not initialise" in detail
        assert "libnvidia-ml" not in detail
