name: "CD: Deploying Validator (dev) with Manual Trigger"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dockerhub-dev
    env:
      TAG: "dev" 
      TARGET_FILE: "docker-compose.app.dstacktee.dev.yml"

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_DEV_PAT }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_DEV_USERNAME }}
        run: echo "$DOCKERHUB_PAT" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Make scripts executable
        run: |
          chmod +x neurons/validators/docker_publish.sh
          chmod +x neurons/validators/docker_runner_publish.sh
          
      - name: Run docker_publish.sh
        run: |
          cd neurons/validators
          ./docker_publish.sh
          
      - name: Run docker_runner_publish.sh
        run: |
          cd neurons/validators
          ./docker_runner_publish.sh
